import {ArrowRightOutlined,CalendarOutlined,CheckCircleOutlined,ClockCircleOutlined,ExclamationCircleOutlined,FileDoneOutlined,ProjectOutlined,SafetyCertificateOutlined,TeamOutlined} from '@ant-design/icons';
import {Alert,Button,Card,Col,List,Row,Space,Statistic,Typography} from 'antd';
import {useNavigate} from 'react-router-dom';
import {useAuthStore} from '../../app/store/authStore';
import {roleLabels} from '../../config/roles';
import {Role} from '../../types';
import {PageHeader} from '../../components/PageHeader';
const configs:Record<Role,{stats:[string,number,string][];todos:string[];quick:[string,string][];notice:string}>={
 [Role.TENDERER]:{stats:[['进行中项目',12,'blue'],['待审批事项',4,'orange'],['本月开标',6,'green'],['异常提醒',1,'red']],todos:['智慧园区项目招标文件待确认','办公改造项目需求审批即将超时','2个项目将在三日内截止报名'],quick:[['创建采购项目','/projects'],['查看审批待办','/approvals']],notice:'重点关注：智慧园区项目距投标截止仅剩 3 天。'},
 [Role.AGENT]:{stats:[['受托项目',18,'blue'],['待发布公告',3,'orange'],['本周开标',5,'green'],['待组织评标',2,'red']],todos:['智慧园区项目报名审核待处理','园区物业项目需完成开标准备','设备采购项目评标专家待抽取'],quick:[['编制招标文件','/tender-docs'],['进入开标准备','/opening-preparation']],notice:'今日 14:00 有一场项目协调会，请提前检查招标文件。'},
 [Role.SUPPLIER]:{stats:[['参与项目',8,'blue'],['待缴费用',2,'orange'],['待上传文件',1,'red'],['待开标',3,'green']],todos:['智慧园区项目保证金待缴纳','年度法律服务报名审核中','请在截止前完成投标文件加密测试'],quick:[['浏览可参与项目','/supplier/available-projects'],['处理我的项目','/supplier/my-projects']],notice:'投标文件上传后仍需完成最终提交，请勿只保存草稿。'},
 [Role.EXPERT]:{stats:[['待评项目',2,'blue'],['待签到',1,'orange'],['评分中',1,'red'],['本月已完成',7,'green']],todos:['智慧园区项目将于7月25日14:00开始评标','园区物业项目评分尚未提交'],quick:[['查看待评项目','/expert/pending'],['维护个人信息','/profile']],notice:'请提前检查CA证书和签名环境，避免影响评标报告签署。'},
 [Role.SUPERVISOR]:{stats:[['待监督开标',3,'blue'],['待监督评标',2,'orange'],['本月已完成',9,'green'],['异常事件',1,'red']],todos:['智慧园区项目开标监督任务待确认','园区物业评标存在评分差异提醒'],quick:[['查看开标任务','/supervision/opening'],['查看异常记录','/supervision/exceptions']],notice:'监督账号仅具备查看与记录权限，不允许修改业务数据。'},
 [Role.ADMIN]:{stats:[['平台用户',1286,'blue'],['待审核供应商',12,'orange'],['入库专家',386,'green'],['系统告警',2,'red']],todos:['12家供应商准入资料待审核','3位专家资质变更待复核','短信服务余额低于预警值'],quick:[['管理用户权限','/system/users'],['维护参数字典','/system/dictionaries']],notice:'演示角色切换器仅用于开发验收，接入真实登录后必须移除。'}
};
export function DashboardPage(){const user=useAuthStore(s=>s.user)!;const c=configs[user.role];const nav=useNavigate();const icons=[<ProjectOutlined/>,<ClockCircleOutlined/>,<CheckCircleOutlined/>,<ExclamationCircleOutlined/>];return <><PageHeader title={`${roleLabels[user.role]}工作台`} description={`你好，${user.name}。这里是你今天需要优先处理的事项。`}/><Alert showIcon message={c.notice} type="info"/><Row gutter={[16,16]} className="stats-row">{c.stats.map(([title,value],i)=><Col span={6} key={title}><Card><Statistic title={title} value={value} prefix={icons[i]}/></Card></Col>)}</Row><Row gutter={16}><Col span={15}><Card title="我的待办" extra={<Button type="link">查看全部</Button>}><List dataSource={c.todos} renderItem={(item,i)=><List.Item actions={[<Button type="link" key="go">立即处理 <ArrowRightOutlined/></Button>]}><List.Item.Meta avatar={i===0?<FileDoneOutlined/>:<CalendarOutlined/>} title={item} description={i===0?'优先级：高 · 今日截止':'来自业务流程的自动提醒'}/></List.Item>}/></Card></Col><Col span={9}><Card title="快捷入口"><Space direction="vertical" className="quick-list">{c.quick.map(([label,path])=><Button key={label} block onClick={()=>nav(path)}>{label}</Button>)}<Button block icon={<TeamOutlined/>}>查看协作人员</Button><Button block icon={<SafetyCertificateOutlined/>}>安全与CA检测</Button></Space></Card></Col></Row></>}
